indigo-web/cdmi/urls.py
""""CDMI URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)
from rest_framework.urlpatterns import format_suffix_patterns
from cdmi import views


urlpatterns = [
   url(r'^cdmi_capabilities(?P<path>.*)$', 'cdmi.views.capabilities', name='capabilities'),
   url(r'^cdmi_objectid/(?P<id>.*)$', 'cdmi.views.crud_id', name='crud_id'),
   
   url(r'^(?P<path>.*)$', views.CDMIView.as_view(), name="api_cdmi"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

indigo-web/indigo_ui/urls.py
""""Indigo UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'indigo_ui.views.home', name='home'),
    url(r'^archive/', include('archive.urls', namespace="archive")),
    url(r'^node/', include('nodes.urls', namespace="nodes")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^groups/', include('groups.urls', namespace="groups")),
    url(r'^activity/', include('activity.urls', namespace="activity")),

    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^api/cdmi/', include('cdmi.urls', namespace="cdmi")),
    url(r'^api/admin/', include('admin.urls', namespace="admin")),
    url(r'^api/triple/', include('triple_api.urls', namespace="triple_api")),
    url(r'^triple/', include('triple_ui.urls', namespace="triple_ui")),
    url(r'^listener/', include('listener.urls', namespace="listener")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

indigo-web/users/urls.py
""""Users UI URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'users.views.home', name='home'),
    url(r'^login$', 'users.views.userlogin', name='auth_login'),
    url(r'^logout$', 'users.views.userlogout', name='auth_logout'),
    
    url(r'^new/user$', 'users.views.new_user', name='new_user'),
    url(r'^delete/user/(?P<name>.*)$', 'users.views.delete_user', name='delete_user'),
    url(r'^edit/user/(?P<name>.*)$', 'users.views.edit_user', name='edit_user'),
    
    url(r'^(?P<name>.*)$', 'users.views.user_view', name='view'),
    

]

indigo-web/users/models.py
"""

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

indigo-web/users/forms.py
"""

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django import forms

class UserForm(forms.Form):

    username = forms.CharField(label='Username', max_length=100, required=True)
    email = forms.CharField(label='Email', max_length=100, required=True)
    active = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    administrator = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

indigo-web/users/views.py
"""

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.contrib import messages
from django.conf import settings

from indigo.models import (
    Group,
    User
)
import ldap

from users.forms import UserForm

def notify_agent(user_id, event=""):
    from nodes.client import choose_client
    client = choose_client()
    client.notify(user_id, event)

@login_required
def home(request):
    # TODO: Order by username
    user_objs = list(User.objects.all())

    paginator = Paginator(user_objs, 10)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        users = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        users = paginator.page(paginator.num_pages)

    ctx = {
        "user": request.user,
        "users": users,
        "user_count": len(user_objs)
    }
    return render(request, 'users/index.html', ctx)

def userlogin(request):
    from django.contrib.auth import login

    if request.method == "GET":
        return render(request, 'users/login.html', {})

    errors = ""
    username = request.POST.get('username')
    password = request.POST.get('password')

    invalid = "Username/Password not valid"

    if not username or not password:
        errors = "Username and password are required"

    if not errors:
        user = User.find(username)
        if not user:
            errors = invalid
        else:
            if not user.authenticate(password) and not ldapAuthenticate(username, password):
                errors = invalid

        if not errors:
            request.session['user'] = unicode(user.name)
            return redirect("/")

    ctx = {}
    if errors:
        ctx = {'errors': errors}


    return render(request, 'users/login.html', ctx)

def ldapAuthenticate(username, password):
    if settings.AUTH_LDAP_SERVER_URI is None:
        return False

    if settings.AUTH_LDAP_USER_DN_TEMPLATE is None:
        return False

    try:
        connection = ldap.initialize(settings.AUTH_LDAP_SERVER_URI)
        connection.protocol_version = ldap.VERSION3
        user_dn = settings.AUTH_LDAP_USER_DN_TEMPLATE % {"user": username}
        connection.simple_bind_s(user_dn, password)
        return True
    except ldap.INVALID_CREDENTIALS:
        return False
    except ldap.SERVER_DOWN:
        # TODO: Return error instead of none
        return False


@login_required
def delete_user(request, name):
    user = User.find(name)
    if not user:
        raise Http404

    if not request.user.administrator:
        raise PermissionDenied

    if request.method == "POST":
        user.delete(username=request.user.name)
        messages.add_message(request, messages.INFO,
                             "The user '{}' has been deleted".format(user.name))
        return redirect('users:home')

    # Requires delete on user
    ctx = {
        "user": user,
    }

    return render(request, 'users/delete.html', ctx)

@login_required
def edit_user(request, name):
    # Requires edit on user
    user = User.find(name)
    if not user:
        raise Http404()

    if not request.user.administrator:
        raise PermissionDenied

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user.update(email=data['email'],
                        administrator=data['administrator'],
                        active=data['active'],
                        username=request.user.name)
            if data["password"] != user.password:
                user.update(password=data["password"],
                            username=request.user.name)
            return redirect('users:home')
    else:
        initial_data = {'username': user.name,
                        'email': user.email,
                        'administrator': user.administrator,
                        "active": user.active,
                        "password": user.password
                       }
        form = UserForm(initial=initial_data)

    ctx = {
        "form": form,
        "user": user,
    }

    return render(request, 'users/edit.html', ctx)


@login_required
def new_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.create(name=data.get("username"),
                        # TODO: Check if we can't harmonize unicode use for passwords between django and CLI
                        password=data.get("password").encode("ascii", "ignore"),
                        email=data.get("email", ""),
                        administrator=data.get("administrator", False),
                        active=data.get("active", False),
                        username=request.user.name)
            messages.add_message(request, messages.INFO,
                             "The user '{}' has been created".format(user.name))
            return redirect('users:home')
    else:
        form = UserForm()

    ctx = {
        "form": form,
    }
    return render(request, 'users/new.html', ctx)

def userlogout(request):
    request.session.flush()
    request.user = None
    return render(request, 'users/logout.html', {})

@login_required
def user_view(request, name):
    # argument is the login name, not the uuid in Cassandra
    user = User.find(name)
    if not user:
        return redirect('users:home')
        #raise Http404

    ctx = {
        "req_user": request.user,
        "user_obj": user,
        "groups": [Group.find(gname) for gname in user.groups]
    }
    return render(request, 'users/view.html', ctx)

indigo-web/users/templates/users/delete.html
{% extends "archive/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="users" %}
{% endblock sidebar %}

{% block title %}Delete User - {{user.uname}}{% endblock title %}

{% block main_content %}

    <h2>Delete User - {{user.name}}</h2>

    <br/><br/>

    <div style="text-align:center; margin-top: 20px;">
        <div style='font-size: 1.5em'>
        Are you sure you wish to delete user {{user.name}}?
        </div>

        <form action="{% url 'users:delete_user' name=user.name %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Delete this user</button>
            <a href="{% url 'users:home' %}" class="btn btn-lg btn-success">Cancel</a>
        </form>

    </div>
{% endblock main_content %}

indigo-web/users/templates/users/edit.html
{% extends "archive/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="users" %}
{% endblock sidebar %}


{% block title %}Edit User - {{user.name}}{% endblock title %}

{% block main_content %}

<h2>Edit User - {{user.name}}
    <a class="pull-right btn btn-default" href="{% url 'users:home' %}">
    &laquo; Back to user management
    </a>
</h2>
<hr/>

{% include "users/user_form.html" with form=form user=user action='edit'%}

{% endblock main_content %}

indigo-web/users/templates/users/index.html
{% extends "base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="users" %}
{% endblock sidebar %}

{% block title %}Users{% endblock title %}

{% block main_content %}
    <h2>Users ({{ user_count }})</h2><hr/>

	{% if user.administrator %}
	<div class="row">
	  <div class="pull-right">
	    <a class="btn btn-sm btn-success" href="{% url 'users:new_user' %}">Add new user</a>
	    
	  </div>
	</div>
	<hr/>
	{% endif %}

    {% for u in users %}
        {% include "users/usertab.html" with req_user=user user=u %}
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if users.has_previous %}
                <a href="?page={{ users.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ users.number }} of {{ users.paginator.num_pages }}.
            </span>

            {% if users.has_next %}
                <a href="?page={{ users.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>


{% endblock main_content %}

indigo-web/users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<div class="row">
  <br/><br/>
  <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">


  {% if errors %}
  <div class="alert alert-danger">
    {{ errors }}
  </div>
  {% endif %}


  <center><h2>Login to Indigo</h2></center>
  <div class="well">
    <form id="loginForm" method="POST" action="{% url 'users:auth_login' %}" novalidate="novalidate">
      {% csrf_token %}
      <div class="form-group">
        <label for="username" class="control-label">Username</label>
        <input type="text" class="form-control" id="username" name="username" value="" required="" title="Please enter you username" placeholder="Username">
        <span class="help-block"></span>
      </div>
      <div class="form-group">
        <label for="password" class="control-label">Password</label>
        <input type="password" class="form-control" id="password" name="password" value="" required="" title="Please enter your password" placeholder="Password">
        <span class="help-block"></span>
      </div>
      <div id="loginErrorMsg" class="alert alert-error hide">Wrong username or password</div>

        <label>
            <input type="hidden" name="remember" id="remember" checked="checked">
        </label>

      <button type="submit" class="btn btn-success btn-block">Login</button>
      <!--<a href="/accounts/forgot/" class="btn btn-default btn-block">Forgotten password</a>-->
    </form>
  </div>
 </div>
</div>


{% endblock %}

{% block extra_javascript %}
  <script type="text/javascript">
  $(document).ready(function (){$('#username').focus();});
  </script>
{% endblock extra_javascript %}

indigo-web/users/templates/users/logout.html
{% extends "base.html" %}


{% block title %}Logged out{% endblock %}

{% block content %}
    <div class="jumbotron"  style="margin-top: 80px;">
      <h2>Logged out</h2>
      <p>You have been logged out and will be redirected to the homepage in 10 seconds</p>

      <p>
        <a class="btn btn-primary" href="/">Go to the homepage</a>
        <a class="btn btn-success" href="{% url 'users:auth_login' %}">Login again</a>
      </p>
    </div>
{% endblock %}


{% block extra_header %}
    <meta http-equiv="refresh" content="10; url=/" />
{% endblock extra_header %}

indigo-web/users/templates/users/new.html
{% extends "archive/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="users" %}
{% endblock sidebar %}


{% block title %}New User{% endblock title %}

{% block main_content %}

<h2>New User
    <a class="pull-right btn btn-default" href="{% url 'users:home' %}">
    &laquo; Back to User list
    </a>
    </h2>
<hr/>

{% include "users/user_form.html" with form=form action='new' %}

{% endblock main_content %}

indigo-web/users/templates/users/user_form.html
{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}

{% if action == 'edit' %}
    {% url 'users:edit_user' name=user.name as post_url %}
{% else %}
    {% url 'users:new_user' as post_url %}
{% endif %}

<form id="loginForm" method="POST" action="{{post_url}}" novalidate="novalidate" enctype="multipart/form-data">
    {% csrf_token %}
    
<!--     {{ form }} -->

	{% if action == 'edit' %}
	    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
	        <label for="username" class="control-label">Username</label>
	        <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:''}}"  title="Enter the username" placeholder="User name" readonly>
	    </div>
	{% else %}
	    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
	        <label for="username" class="control-label">Username</label>
	        <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:''}}"  title="Enter the username" placeholder="User name">
	    </div>
	{% endif %}
    
    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="email" class="control-label">Email</label>
        <input type="text" class="form-control" id="email" name="email" value="{{form.email.value|default:''}}"  title="Enter the email" placeholder="Email of user">
    </div>
       
    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="active" class="control-label">Active</label>
        {% if action == 'edit' %}
            <input {% if user.active %}checked="checked"{% endif %} type="checkbox" name="active" id="active" />
        {% else %}
            <input checked="checked" type="checkbox" name="active" id="active" />
        {% endif %}
        
    </div>
        
     <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="administrator" class="control-label">Administrator</label>
        {% if action == 'edit' %}
            <input {% if user.administrator %}checked="checked"{% endif %} type="checkbox" name="administrator" id="administrator" />
        {% else %}
            <input type="checkbox" name="administrator" id="administrator" />
        {% endif %}
     </div>
     
     <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="password" class="control-label">Password</label>
        <input type="password" size="10" class="form-control" id="password" name="password" value="{{form.password.value|default:''}}"  title="Enter the password" placeholder="Password of user">
    </div>

    <button type="submit" class="btn btn-success btn-block">Save</button>
</form>

indigo-web/users/templates/users/usertab.html
{% load gravatar %}

<div class="col-md-3" >
    <table width="100%" border="0" class="table user-tab" style="table-layout:fixed;" cellpadding="0" cellspacing="0">
        <tr>
            <td>
            {% gravatar user.email 60 %}
            </td>
            <td valign="top" align="left">
                <a href="{% url 'users:view' name=user.name %}">
                {{ user.name }}
                </a>
                
                {% if req_user.administrator %}
                  <a href="{% url 'users:edit_user' name=user.name %}" >
                  <i class="blue-icon glyphicon glyphicon-pencil"></i>
                  </a>
                  <a href="{% url 'users:delete_user' name=user.name %}">
                  <i class="blue-icon glyphicon glyphicon-remove-circle"></i>
                  </a>
                 {% endif %}
            </td>
        </tr>
    </table>
</div>

indigo-web/users/templates/users/view.html
{% extends "base.html" %}
{% load gravatar %}

{% block title %}Users - {{user_obj.name}}{% endblock title %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="users" %}
{% endblock sidebar %}


{% block main_content %}
    <h2>{% gravatar user_obj.email 40 %} {{ user_obj.name }}</h2>

    <hr/>
    <h3>Profile</h3>

    <div>
        {% if req_user.administrator %}
          <div>
              <strong>Active:</strong> <input type="checkbox" name="active" {% if user_obj.active %}checked{% endif %} />
          </div>
          <div>
              <strong>Administrator:</strong> <input type="checkbox" name="active" {% if user_obj.administrator %}checked{% endif %} />
          </div>
        {% endif %}
        
        <div>
            <strong>Email:</strong> {{ user_obj.email|default:"Private"}}
        </div>
        
        {% if req_user.administrator %}
        <div>
          <strong>Groups:</strong>
          <ul>
          {% for g in groups %}
            <li>
              <a href="{% url 'groups:view' name=g.name %}">{{g.name}}</a>
            </li>
          {% endfor %}
          </ul>
        </div>
        {% endif %}
    </div>


{% endblock main_content %}