indigo-web/archive/urls.py
"""Archive URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'archive.views.home', name='home'),
    url(r'^search$', 'archive.views.search', name='search'),
    url(r'^search2$', 'archive.views.search2', name='search2'),

    url(r'^resource(?P<path>.*)$', 'archive.views.view_resource', name='resource_view'),
    url(r'^new/collection(?P<parent>.*)$', 'archive.views.new_collection', name='new_collection'),
    url(r'^edit/collection(?P<path>.*)$', 'archive.views.edit_collection', name='edit_collection'),
    url(r'^delete/collection(?P<path>.*)$', 'archive.views.delete_collection', name='delete_collection'),

    url(r'^new/resource(?P<parent>.*)$', 'archive.views.new_resource', name='new_resource'),
    url(r'^edit/resource(?P<path>.*)$', 'archive.views.edit_resource', name='edit_resource'),
    url(r'^delete/resource(?P<path>.*)$', 'archive.views.delete_resource', name='delete_resource'),

    url(r'^view(?P<path>.*)$', 'archive.views.view_collection', name='view'),
    url(r'^download(?P<path>.*)$', 'archive.views.download', name='download'),
    url(r'^preview(?P<path>.*)$', 'archive.views.preview', name='preview'),
]

indigo-web/cdmi/urls.py
""""CDMI URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)
from rest_framework.urlpatterns import format_suffix_patterns
from cdmi import views


urlpatterns = [
   url(r'^cdmi_capabilities(?P<path>.*)$', 'cdmi.views.capabilities', name='capabilities'),
   url(r'^cdmi_objectid/(?P<id>.*)$', 'cdmi.views.crud_id', name='crud_id'),
   
   url(r'^(?P<path>.*)$', views.CDMIView.as_view(), name="api_cdmi"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

indigo-web/indigo_ui/urls.py
""""Indigo UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'indigo_ui.views.home', name='home'),
    url(r'^archive/', include('archive.urls', namespace="archive")),
    url(r'^node/', include('nodes.urls', namespace="nodes")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^groups/', include('groups.urls', namespace="groups")),
    url(r'^activity/', include('activity.urls', namespace="activity")),

    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^api/cdmi/', include('cdmi.urls', namespace="cdmi")),
    url(r'^api/admin/', include('admin.urls', namespace="admin")),
    url(r'^api/triple/', include('triple_api.urls', namespace="triple_api")),
    url(r'^triple/', include('triple_ui.urls', namespace="triple_ui")),
    url(r'^listener/', include('listener.urls', namespace="listener")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

indigo-web/archive/models.py
"""Archive Models

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.db import models

indigo-web/archive/forms.py
"""Archive Forms

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django import forms
import json

from indigo.metadata import (
    get_collection_validator,
    get_resource_validator
)

from archive.widgets import JsonPairInputs


def get_groups():
    from indigo.models import Group
    return [(u'AUTHENTICATED@', 'authenticated@'),
            (u'ANONYMOUS@', 'anonymous@')] + [(g.name,g.name,) for g in Group.objects.all()]

class CollectionForm(forms.Form):
    groups = get_groups

    metadata = forms.CharField(label="Metadata", required=False,
                               widget=JsonPairInputs())
    read_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    write_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    edit_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    delete_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)

    def clean_metadata(self):
        data = self.cleaned_data['metadata']
        dct = {}
        for l in json.loads(data):
            dct[l[0]] = l[1]

        ok, errs = get_collection_validator().validate(dct)
        if not ok:
            raise forms.ValidationError([forms.ValidationError(e) for e in errs])
        return data


class CollectionNewForm(CollectionForm):
    name = forms.CharField(label='Collection name', max_length=100, required=True)

class ResourceForm(forms.Form):
    groups = get_groups

    metadata = forms.CharField(label="Metadata", required=False,
                               widget=JsonPairInputs())
    read_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    write_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    edit_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    delete_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)

    def clean_metadata(self):
        data = self.cleaned_data['metadata']
        dct = {}
        for l in json.loads(data):
            dct[l[0]] = l[1]

        ok, errs = get_resource_validator().validate(dct)
        if not ok:
            raise forms.ValidationError([forms.ValidationError(e) for e in errs])
        return data


class ResourceNewForm(ResourceForm):
    name = forms.CharField(label='Item name', max_length=100, required=True)
    file = forms.FileField(required=True)

indigo-web/archive/templates/archive/resource/delete.html
{% extends "archive/base.html" %}

{% block title %}Delete Item - {{resource.name}}{% endblock title %}

{% block main_content %}

    <h2>Delete Item - {{resource.name}}</h2>

    <br/><br/>

    <div style="text-align:center; margin-top: 20px;">
        <div style='font-size: 1.5em'>
        Are you sure you wish to continue?
        </div>

        <form action="{% url 'archive:delete_resource' path=resource.path %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Delete this item</button>
            <a href="{% url 'archive:view' path=container.path %}" class="btn btn-lg btn-success">Cancel</a>
        </form>

    </div>
{% endblock main_content %}

indigo-web/archive/templates/archive/resource/edit.html
{% extends "archive/base.html" %}

{% block title %}Edit Item - {{resource.name}}{% endblock title %}

{% block main_content %}

<h2>Edit Item - {{resource.name}}
    <a class="pull-right btn btn-default" href="{% url 'archive:view' path=collection.path %}">
    &laquo; Back to '{{ container.name }}' collection
    </a>
</h2>
<hr/>

{% include "archive/resource/resource_form.html" with form=form container=container resource=resource groups=groups action='edit'%}

{% endblock main_content %}

indigo-web/archive/templates/archive/resource/new.html
{% extends "archive/base.html" %}

{% block title %}New Item in '{{ container.name }}'{% endblock title %}

{% block main_content %}

<h2>New Item in '{{ container.name }}'
    <a class="pull-right btn btn-default" href="{% url 'archive:view' path=parent.path %}">
    &laquo; Back to '{{ container.name }}' collection
    </a>
    </h2>
<hr/>

{% include "archive/resource/resource_form.html" with form=form groups=groups container=container  action='new' %}

{% endblock main_content %}

indigo-web/archive/templates/archive/resource/resource_entry.html
<div class="resource-entry">

  <div class="row">
      {% if resource.can_delete %}
        <a href="{% url 'archive:delete_resource' path=resource.path %}">
        <i class="blue-icon glyphicon glyphicon glyphicon-remove-circle"></i>
        &nbsp;&nbsp;
        </a>
      {% endif %}
      {% if resource.can_read %}
      <i class="label label-info">{{resource.type|default:"Unknown"}}</i>
      &nbsp;
      <a href="{% url 'archive:resource_view' path=resource.path %}">
        {{ resource.name }}
      </a>
      {% else %}
        <span style="color: #999">
         <i class="label label-default">{{resource.type|default:"Unknown"}}</i>
         &nbsp;
        {{ resource.name }}
        </span>
      {% endif %}

      {% if resource.can_read %}
      <a class="pull-right" href="{% url 'archive:download' path=resource.path%}" >
      Download  <i class="glyphicon glyphicon-download-alt"></i>
      </a>
      {% endif %}
  </div>

  {% if resource.metadata %}
      {% if resource.can_read %}
        <div class="row">
        {% for m in resource.metadata %}
          {% if m.0|length > 10 or m.1|length > 10 %}
            <span class="label label-{% if not resource.can_read %}default{% else %}success{% endif %}" data-toggle="tooltip" title="{{ m.0 }} = {{ m.1 }}">
                 ...
            </span>&nbsp;&nbsp;
          {% else %}
             <span class="label label-{% if not resource.can_read %}default{% else %}success{% endif %}">
             {{ m.0 }} = {{ m.1 }}
             </span>&nbsp;&nbsp;
          {% endif %}
        {% endfor %}
        </div>
     {% endif %}
  {% endif %}
</div>
<hr/>

indigo-web/archive/templates/archive/resource/resource_form.html
{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}

{% if action == 'edit' %}
    {% url 'archive:edit_resource' path=resource.path as post_url %}
{% else %}
    {% url 'archive:new_resource' container=container.path as post_url %}
{% endif %}


<form id="loginForm" method="POST" action="{{post_url}}" novalidate="novalidate" enctype="multipart/form-data">
    {% csrf_token %}
    {% if action == 'new' %}
        <div class="form-group {% if form.errors.name %}has-error{% endif %}">
            <label for="name" class="control-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{form.name.value|default:''}}"  title="Enter the item name" placeholder="Name of item">
        </div>
    {% endif %}

    {% if action != 'edit' %}
        <div class="well form-group {% if form.errors.file %}has-error{% endif %}">
                {# We remove the "fakepath" bit because Chrome is odd. See: http://davidwalsh.name/fakepath #}
                <input type="file" name="file" onchange="if ($('#name').val()=='') {$('#name').val(this.value.replace('C:\\fakepath\\', ''))}"/>
        </div>
    {% endif %}

    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-md-3">
            <strong>Read permission</strong>
            <div class="checkbox">
                {{form.read_access}}
            </div>
        </div>
        <div class="col-md-3 left-border">
            <strong>Write permission</strong>
            <div class="checkbox">
                {{form.write_access}}
            </div>
        </div>
    </div>

    <h4>Metadata</h4>

    <div class="form-group {% if form.errors.metadata %}has-error{% endif %}">
    {% if form.errors.metadata %}
    <div class="alert alert-danger">{{form.errors.metadata}}</div>
    {% endif %}
    {{form.metadata}}
    </div>

    <button type="submit" class="btn btn-success btn-block">Save</button>
</form>

<script type="text/javascript">
$(document).ready(function(){
    $('#name').focus();

    var mf_fields_count = $("#metadata_fields .form-group").size()

    function setminus_visibile_on_first_row() {
        var first = $("#metadata_fields .form-group").get(0);
        var btn = $(first).find(".btn-danger");

        console.log(mf_fields_count.toString());
        if (mf_fields_count <= 1) {
            btn.hide();
        } else {
            btn.show();
        }

    }

    function clone_and_clean(element) {
        var obj = element.clone()

        var inputs = $(obj).find("input");
        inputs.each(function(idx, input){
            $(this).val("");
        });


        return obj;
    }

    function prep(container, index, value) {
        var minus = $(container).find('.btn-danger');
        var plus  = $(container).find('.btn-success');

        minus.click(function(){
            $(container).remove();
            mf_fields_count -= 1;
            setminus_visibile_on_first_row();
        });

        plus.click(function(){
            var newrow = clone_and_clean($(container));
            newrow.appendTo($(container).parent());

            mf_fields_count += 1;
            prep(newrow, mf_fields_count-1, "" );
            setminus_visibile_on_first_row();
        });

        if(index == 0) {
            minus.hide();
        } else {
            minus.show();
        }
    }

    function update_name() {
        alert("update");
    }


    $("#metadata_fields .form-group").each(function(index, value){
        var that = $(this);
        prep(that, index, value);
    });
});
</script>

<style>
#id_read_access li   { list-style: none; margin-left: -30px; }
#id_write_access li  { list-style: none; margin-left: -30px; }
#id_edit_access li   { list-style: none; margin-left: -30px; }
#id_delete_access li { list-style: none; margin-left: -30px; }
#id_read_access   { margin-top: 10px; }
#id_write_access  { margin-top: 10px; }
#id_edit_access   { margin-top: 10px; }
#id_delete_access { margin-top: 10px; }
.left-border { border-left: solid 1px #eee; }
</style>

indigo-web/archive/templates/archive/resource/view.html
{% extends "archive/base.html" %}

{% block title %}Item - {{resource.name}}{% endblock title %}

{% block main_content %}

<h2>Item - {{resource.name}}
        <a class="btn btn-success pull-right" href="{% url 'archive:download' path=resource.path %}">Download file</a>

</h2>
<hr/>


<ol class="breadcrumb">
  <li><a href="{% url 'archive:view' path="" %}">Home</a></li>
  {% for coll,full in collection_paths %}
    {% if forloop.last %}
        <li class="active"><a href="{% url 'archive:view' path=full %}">{{coll}}</a></li>
    {% else %}
        <li><a href="{% url 'archive:view' path=full %}">{{coll}}</a></li>
    {% endif %}
  {% endfor %}
</ol>


{# Permission check for action bar .... #}

    <div class="control-bar">
        {% if resource.can_edit %}
        <a class="btn btn-info" href='{% url "archive:edit_resource" path=resource.path %}'%}>Edit Item</a>
        {% endif %}
        {% if resource.can_delete %}
        <a class="btn btn-danger" href='{% url "archive:delete_resource" path=resource.path %}'>Delete Item</a>
        {% endif %}

        <div class="clearfix"></div>
    </div>

    <hr/>



<div class="col-md-6">
    <h4>Preview</h4>
    <hr/>
    <iframe src="{% url 'archive:preview' path=resource.path%}" style="width:420px; height: 560px; border: none;" >
    </iframe>
</div>

<div class="col-md-6">
    <h4>Metadata</h4>
    <hr/>
    <table class="table table-">
    <tbody>
        <tr><th style="border-bottom: solid 2px #eee;" colspan="2">Core metadata</th></tr>
        <tr>
            <th>Name</th>
            <td>{{resource.name}}</td>
        </tr>
        <tr>
            <th>Mimetype</th>
            <td>{{resource.mimetype|default:"Not set"}}</td>
        </tr>
        {% if resource.size %}
        <tr>
            <th>Size (in bytes)</th>
            <td>{{resource.size|default:"Not set"}}</td>
        </tr>
        {% endif %}
        <tr>
            <th>Collection</th>
            <td><a href="/archive/view{{ container_path }}">{{ container.name }}</a></td>
        </tr>
        {% if resource.create_ts %}
        <tr>
            <th>Created date/time</th>
            <td>{{resource.create_ts}}</td>
        </tr>
        {% endif %}
        {% if resource.modified_ts %}
        <tr>
            <th>Modified date/time</th>
            <td>{{resource.modified_ts}}</td>
        </tr>
        {% endif %}
        <tr>
            <th>CDMI URL:</th>
            <td><a href='{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}/api/cdmi{{resource.path}}'>
              {% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}/api/cdmi{{resource.path}}
               </a></td>
        </tr>
        {% if resource.is_reference %}
            <tr>
                <th>Reference:</th>
                <td><a href="{{resource.url}}">{{resource.url}}</a></td>
            </tr>
        {% endif %}
        
       {% if request.user.administrator and not resource.is_reference %}
        <tr>
            <th>Internal URL</th>
            <td>{{resource.url}}</td>
        </tr>
        {% endif %}
        {% if resource.metadata|length %}
            <tr><th style="border-bottom: solid 2px #eee;" colspan="2">Custom metadata</th></tr>
        {% endif %}
        {% for row in resource.metadata %}
        <tr>
          <th>
            {% if row.0|length > 10 %}
              <span data-toggle="tooltip" title="{{ row.0 }}">...</span>
            {% else %}
              {{ row.0 }}
            {% endif %}
          </th>
          <td>
            {% if row.1|length > 10 %}
              <span data-toggle="tooltip" title="{{ row.1 }}">...</span>
            {% else %}
              {{ row.1 }}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% endblock main_content %}