indigo-web/cdmi/urls.py
""""CDMI URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)
from rest_framework.urlpatterns import format_suffix_patterns
from cdmi import views


urlpatterns = [
   url(r'^cdmi_capabilities(?P<path>.*)$', 'cdmi.views.capabilities', name='capabilities'),
   url(r'^cdmi_objectid/(?P<id>.*)$', 'cdmi.views.crud_id', name='crud_id'),
   
   url(r'^(?P<path>.*)$', views.CDMIView.as_view(), name="api_cdmi"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

indigo-web/indigo_ui/urls.py
""""Indigo UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'indigo_ui.views.home', name='home'),
    url(r'^archive/', include('archive.urls', namespace="archive")),
    url(r'^node/', include('nodes.urls', namespace="nodes")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^groups/', include('groups.urls', namespace="groups")),
    url(r'^activity/', include('activity.urls', namespace="activity")),

    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^api/cdmi/', include('cdmi.urls', namespace="cdmi")),
    url(r'^api/admin/', include('admin.urls', namespace="admin")),
    url(r'^api/triple/', include('triple_api.urls', namespace="triple_api")),
    url(r'^triple/', include('triple_ui.urls', namespace="triple_ui")),
    url(r'^listener/', include('listener.urls', namespace="listener")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

indigo-web/triple_ui/urls.py
""""Fact URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)


from . import views

urlpatterns = [
   url(r'^$', views.home, name='home'),
   url(r'^view/(?P<repository>.*)/listPublicImages$', views.view_public_images, name='view_public_images'),
   url(r'^view/(?P<repository>.*)$', views.view, name='view'),
   
    url(r'^new/repository$', views.new, name='new_repository'),
    url(r'^delete/repository/(?P<repository>.*)$', views.delete, name='delete_repository'),
    url(r'^delete/statements/(?P<repository>.*)$', views.delete_statements, name='delete_statements'),
    url(r'^add/repository/(?P<repository>.*)$', views.add_statements, name='add_statements'),
   
]

indigo-web/triple_ui/models.py
from django.db import models

# Create your models here.

indigo-web/triple_ui/forms.py
from django import forms

class RepositoryForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)


class AddStatementsForm(forms.Form):
    file = forms.FileField()


class QueryRepositoryForm(forms.Form):
    query = forms.CharField(label='Query', max_length=500, required=True)

indigo-web/triple_ui/views.py
""""Triple UI views

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.utils.translation import ugettext_lazy as _
from django.shortcuts import (
    render,
    redirect
)
from django.core.files.uploadhandler import TemporaryFileUploadHandler

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import (
    csrf_exempt,
    csrf_protect
)
from django.core.exceptions import PermissionDenied
from triple_ui.forms import (
    AddStatementsForm,
    QueryRepositoryForm,
    RepositoryForm
)
from django.contrib import messages

from triple_models.allegro_repository import (
    add_repository_statements,
    create_repository,
    delete_repository,
    delete_repository_statements,
    list_repositories,
    query_repository,
    list_public_images
)



@login_required()
def home(request):
    ok, ls_infos, _, msg = list_repositories()
    if not ok:
        messages.add_message(request, messages.ERROR, msg)
    ctx = {
        'is_admin': request.user.administrator,
        'repositories': [el.get('title', '') for el in ls_infos]
    }
    return render(request, 'triple_ui/repositories.html', ctx)


@login_required()
def view(request, repository):
    query = "select ?subject ?predicate ?object {?subject ?predicate ?object}"
    if request.method == 'POST':
        form = QueryRepositoryForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            query = data['query']
    else:
        form = QueryRepositoryForm()
    
    ok, r, _, msg = query_repository(repository, query)
    if not ok:
        messages.add_message(request, messages.ERROR, msg)
    ctx = {
        "form": form,
        'is_admin': request.user.administrator,
        'repository': repository,
        'results': r.json(),
        'query': query
    }
    return render(request, 'triple_ui/repository.html', ctx)

@login_required()
def view_public_images(request, repository):
    ok, r, _, msg = list_public_images(repository)
    ls = [ el[0].replace('"', '') for el in r.json().get('values', []) ]
    
    ctx = { 'repository': repository,
            'results': ls}
    return render(request, 'triple_ui/public_images.html', ctx)

@login_required()
def delete_statements(request, repository):
    if request.method == "POST":
        ok, _, _, msg = delete_repository_statements(repository)
        if not ok:
            messages.add_message(request, messages.ERROR, msg)
        else:
            messages.add_message(request, messages.INFO,
                                 "Statements have been deleted")
        #edited_repository_signal.send(None, user=request.user, repository=repository)
        return redirect('triple_ui:view', repository=repository)

    return render(request, 'triple_ui/delete_statements.html', {'repository': repository})


@csrf_exempt
def add_statements(request, repository):
    request.upload_handlers = [TemporaryFileUploadHandler()]
    return add_statements_real(request, repository)

@login_required()
def add_statements_real(request, repository):
    if request.method == 'POST':
        form = AddStatementsForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            content_type = f.content_type
            # if  the content type is "application/octet-stream" it's probably
            # django which didn't find the right one, try with "
            if content_type == "application/octet-stream":
                content_type = "text/plain"
                if f.name.endswith(".ttl"):
                    content_type = "text/turtle"
                elif f.name.endswith(".xml"):
                    content_type = "application/rdf+xml"
            ok, _, _, msg = add_repository_statements(repository, f, content_type,
                                                   True)
            if not ok:
                messages.add_message(request, messages.ERROR, msg)
            else:
                messages.add_message(request, messages.INFO,
                                     "Statements have been added")
                #edited_repository_signal.send(None, user=request.user, repository=repository)
            return redirect('triple_ui:view', repository=repository)
    else:
        form = AddStatementsForm()

    ctx = {
        "form": form,
        "repository": repository,
    }
    return render(request, 'triple_ui/add_statements.html', ctx)


@login_required()
def delete(request, repository):
    if request.method == "POST":
        ok, _, _, msg = delete_repository(repository)
        if not ok:
            messages.add_message(request, messages.ERROR, msg)
        else:
            messages.add_message(request, messages.INFO,
                                 "The repository '{}' has been deleted".format(repository))
        #delete_repository_signal.send(None, user=request.user, repository=repository)
        return redirect('triple_ui:home')

    return render(request, 'triple_ui/delete_repo.html', {'repository': repository})



@login_required
def new(request):
#     # User must be able to create a repository ?
#     if not request.user.administrator:
#         raise PermissionDenied

    if request.method == 'POST':
        form = RepositoryForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            repository = data['name']
            ok, _, _, msg = create_repository(repository)
            if not ok:
                messages.add_message(request, messages.ERROR, msg)
            else:
                messages.add_message(request, messages.INFO,
                                 "The repository '{}' has been created".format(repository))
            #new_repository_signal.send(None, user=request.user, repository=repository)
            return redirect('triple_ui:view', repository=repository)
    else:
        form = RepositoryForm()

    ctx = {
        "form": form,
    }
    return render(request, 'triple_ui/new_repo.html', ctx)

indigo-web/triple_ui/templates/triple_ui/add_statements.html
{% extends "triple_ui/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="triple" %}
{% endblock sidebar %}


{% block title %}Add statements to {{repository}}{% endblock title %}

{% block main_content %}

<h2>Add statements to {{repository}}
    <a class="pull-right btn btn-default" href="{% url 'triple_ui:view' repository=repository %}">
    &laquo; Back to Repository view
    </a>
    </h2>
<hr/>


{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}


{% url 'triple_ui:add_statements' as post_url %}

<form id="loginForm" method="POST" action="{{post_url}}" novalidate="novalidate" enctype="multipart/form-data">
    {% csrf_token %}
    
<!--     {{ form }} -->

    <div class="well form-group {% if form.errors.file %}has-error{% endif %}">
        {# We remove the "fakepath" bit because Chrome is odd. See: http://davidwalsh.name/fakepath #}
        <input type="file" name="file" onchange="$('#name').val(this.value.replace('C:\\fakepath\\', ''))"/>
    </div>
    

    <button type="submit" class="btn btn-success btn-block">Add</button>
</form>


{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/base.html
{% extends "base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="triple" %}
{% endblock sidebar %}

indigo-web/triple_ui/templates/triple_ui/delete_repo.html
{% extends "triple_ui/base.html" %}

{% block title %}Delete Repository - {{repository}}{% endblock title %}

{% block main_content %}

    <h2>Delete Repository - {{repository}}</h2>

    <br/><br/>
    <div style="font-size:1.5em;" class="alert alert-danger">
        <strong>Deleting this repository will delete this repository 
    and all statements within it.</strong>
    </div>

    <div class="row">
    </div>

    <div style="text-align:center; margin-top: 20px;">
        <div style='font-size: 1.5em'>
        Are you sure you wish to continue?
        </div>

        <form action="{% url 'triple_ui:delete_repository' repository=repository %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Delete this repository</button>
            <a href="{% url 'triple_ui:home' %}" class="btn btn-lg btn-success">Cancel</a>
        </form>

    </div>
{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/delete_statements.html
{% extends "triple_ui/base.html" %}

{% block title %}Delete statements of repository - {{repository}}{% endblock title %}

{% block main_content %}

    <h2>Delete statements of repository - {{repository}}</h2>

    <br/><br/>
    <div style="font-size:1.5em;" class="alert alert-danger">
        <strong>This will delete all statements of this repository.</strong>
    </div>

    <div class="row">
    </div>

    <div style="text-align:center; margin-top: 20px;">
        <div style='font-size: 1.5em'>
        Are you sure you wish to continue?
        </div>

        <form action="{% url 'triple_ui:delete_statements' repository=repository %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Delete statements</button>
            <a href="{% url 'triple_ui:view' repository=repository %}" class="btn btn-lg btn-success">Cancel</a>
        </form>

    </div>
{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/new_repo.html
{% extends "triple_ui/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="triple" %}
{% endblock sidebar %}


{% block title %}New Repository{% endblock title %}

{% block main_content %}

<h2>New Repository
    <a class="pull-right btn btn-default" href="{% url 'triple_ui:home' %}">
    &laquo; Back to Repository list
    </a>
    </h2>
<hr/>

{% include "triple_ui/repository_form.html" with form=form action='new' %}

{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/public_images.html
{% extends "triple_ui/base.html" %}

{% block title %}Triple Store{% endblock title %}

{% block main_content %}


<h2>Repository {{ repository }}</h2>

<hr/>


<ol class="breadcrumb">
  <li><a href="{% url 'triple_ui:home' %}">Catalog</a></li>
  <li><a href="{% url 'triple_ui:view' repository=repository %}">{{ repository }}</a></li>
</ol>
<hr/>

<ul>
{% for url in results %}
    <li><img src={{ url }} alt={{ url }} /></li>
{% endfor %}
</ul>


{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/repositories.html
{% extends "triple_ui/base.html" %}

{% block title %}Triple Store{% endblock title %}

{% block main_content %}


<h2>Triple Store</h2>



<ol class="breadcrumb">
  <li><a href="{% url 'triple_ui:home' %}">Catalog</a></li>
</ol>
<hr/>

{% if is_admin %}
<div class="row">
  <div class="pull-right">
    <a class="btn btn-sm btn-success" href="{% url 'triple_ui:new_repository' %}">Add new repository</a>
  </div>
</div>
<hr/>
{% endif %}

{% for repository in repositories %}
  <div class="collection-entry row">
    <div class="col-md-12">
        <a href="{% url 'triple_ui:delete_repository' repository=repository %}">
        <i class="blue-icon glyphicon glyphicon glyphicon-remove-circle"></i>
        &nbsp;&nbsp;
        </a>
      <i class="blue-icon glyphicon glyphicon-folder-open"></i>
      &nbsp;&nbsp;
      <a href="{% url 'triple_ui:view' repository=repository %}">
          {{ repository }}
      </a>
    </div>
  </div>
{% endfor %}

{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/repository.html
{% extends "triple_ui/base.html" %}

{% block title %}Triple Store{% endblock title %}

{% block main_content %}


<h2>Repository {{ repo }}
&nbsp;&nbsp;<a class="btn btn-xs btn-danger" href="{% url 'triple_ui:delete_repository' repository=repository %}">Delete</a>
</h2>

<hr/>

<div >
    <form  style="margin-left: 4px;margin-right: 4px;" action="{% url 'triple_ui:view' repository=repository %}"
           method="POST" novalidate="novalidate" enctype="multipart/form-data">
         {% csrf_token %} 
        <div class="input-group {% if size == 'full' %}input-group-lg{% endif %}">
            <input name="query" type="text" placeholder="{query}}" value="{{query}}"
            class="form-control {% if size == 'full' %}input-lg{% endif %}">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-success">Query</button>
            </span>
        </div>
    </form>
</div>


<hr/>



<ol class="breadcrumb">
  <li><a href="{% url 'triple_ui:home' %}">Catalog</a></li>
  <li><a href="{% url 'triple_ui:view' repository=repository %}">{{ repository }}</a></li>
</ol>
<hr/>

{% if is_admin %}
<div class="row">
  <div class="pull-right">
    <a class="btn btn-sm btn-success" href="{% url 'triple_ui:add_statements' repository=repository %}">Add statements</a>
    <a class="btn btn-sm btn-success" href="{% url 'triple_ui:delete_statements' repository=repository %}">Delete statements</a>
  </div>
</div>
<hr/>
{% endif %}

<h1>{{results.name}}</h1>
<table class="table table-hover" summary="Container contents" border="1">
  <tbody>
    <tr>
    {% for coll_name in results.names %}
      <th>{{coll_name}}</th>
    {% endfor %}
    </tr>
    {% for stat in results.values %}
      <tr>
          <td>{{ stat.0 }}</td>
          <td>{{ stat.1 }}</td>
          <td>{{ stat.2 }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>



{% endblock main_content %}

indigo-web/triple_ui/templates/triple_ui/repository_form.html
{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}


{% url 'triple_ui:new_repository' as post_url %}

<form id="loginForm" method="POST" action="{{post_url}}"
      novalidate="novalidate" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="name" class="control-label">Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{form.name.value|default:''}}"  title="Enter the repository name" placeholder="Name of repository">
    </div>

    <button type="submit" class="btn btn-success btn-block">Save</button>
</form>