indigo-web/cdmi/urls.py
""""CDMI URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)
from rest_framework.urlpatterns import format_suffix_patterns
from cdmi import views


urlpatterns = [
   url(r'^cdmi_capabilities(?P<path>.*)$', 'cdmi.views.capabilities', name='capabilities'),
   url(r'^cdmi_objectid/(?P<id>.*)$', 'cdmi.views.crud_id', name='crud_id'),
   
   url(r'^(?P<path>.*)$', views.CDMIView.as_view(), name="api_cdmi"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

indigo-web/indigo_ui/urls.py
""""Indigo UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'indigo_ui.views.home', name='home'),
    url(r'^archive/', include('archive.urls', namespace="archive")),
    url(r'^node/', include('nodes.urls', namespace="nodes")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^groups/', include('groups.urls', namespace="groups")),
    url(r'^activity/', include('activity.urls', namespace="activity")),

    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^api/cdmi/', include('cdmi.urls', namespace="cdmi")),
    url(r'^api/admin/', include('admin.urls', namespace="admin")),
    url(r'^api/triple/', include('triple_api.urls', namespace="triple_api")),
    url(r'^triple/', include('triple_ui.urls', namespace="triple_ui")),
    url(r'^listener/', include('listener.urls', namespace="listener")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

indigo-web/users/urls.py
""""Users UI URLs

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'users.views.home', name='home'),
    url(r'^login$', 'users.views.userlogin', name='auth_login'),
    url(r'^logout$', 'users.views.userlogout', name='auth_logout'),
    
    url(r'^new/user$', 'users.views.new_user', name='new_user'),
    url(r'^delete/user/(?P<name>.*)$', 'users.views.delete_user', name='delete_user'),
    url(r'^edit/user/(?P<name>.*)$', 'users.views.edit_user', name='edit_user'),
    
    url(r'^(?P<name>.*)$', 'users.views.user_view', name='view'),
    

]

indigo-web/indigo_ui/views.py
""""Indigo UI views

Copyright 2015 Archive Analytics Solutions - University of Liverpool

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.utils.translation import ugettext as _
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout

def home(request):
    if request.user and request.user.is_authenticated():
        return redirect('archive:home')
    return render(request, 'index.html', {})

def login_view(request):
    return render(request, 'login.html', {})

def logout_view(request):
    logout(request)
    messages.info(request, _("You have been logged out of Indigo"))
    return redirect("/")

indigo-web/indigo_ui/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock title %}

{% block content %}
<div class="container">
    <h2>About the Entity Registry Model Repository</h2>
</div>
{% endblock %}

indigo-web/indigo_ui/templates/base.html
{% load ui_tags %}
{% load gravatar %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Pericles - {% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "css/navbar-fixed-top.css" %}' rel="stylesheet">
    <link href='{% static "css/sidebar.css" %}' rel="stylesheet">
    <link href='{% static "css/pericles.css" %}' rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src='{% static "js/ie-emulation-modes-warning.js"%}'></script>
    <script src='{% static "js/jquery.min.js"%}'></script>
    <script src='{% static "js/bootstrap.min.js"%}'></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_header %}
    {% endblock extra_header %}

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>

        {% url 'home' as home %}
        {% url 'about' as about %}
        {% url 'contact' as contact %}
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li {% if request.path == home %}class="active"
            {% endif %}>
              <a href="/">Home</a>
            </li>

            {% if request.user.is_authenticated %}
            
            <li {% if '/archive' in request.path %}class="active"{% endif %}>
                <a href="{% url 'archive:home' %}">Object Store</a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li {% if '/triple' in request.path %}class="active"{% endif %}>
                <a href="{% url 'triple_ui:home' %}">Triple Store</a>
            </li>
            {% endif %}

            <li {% if request.path == about %}class="active"
            {% endif %}>
              <a href="{% url 'about' %}">About</a>
            </li>
            <li {% if request.path == contact %}class="active"
            {% endif %}>
              <a href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if not request.user.is_authenticated %}
                  <li><a href="{% url 'users:auth_login' %}">Login</a></li>
              {% else %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    Welcome, {{ request.user.get_full_name|default:request.user.name }} <span class="pull-left" style="margin-top:-10px;margin-right: 8px;">{% gravatar request.user.email 40 %}</span>
                    <span class="caret"></span>
                  </a>
                   <ul class="dropdown-menu" role="menu">
                    {% if user.administrator %}
                    <li><a href="{% url 'users:home' %}">Users</a></li>
                    {% endif %}

                    <li><a href="{% url 'activity:home' %}">Activity</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'users:auth_logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">


      {% block content %}


      {% if user.is_authenticated %}
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
          <center>
            <br/>
            <a href="/">
              <img src="{% static 'img/logo_80.png' %}" border="0" width="200px"/>
            </a>
          </center>
          <ul class="nav nav-sidebar">
            {% block sidebar %}
            {% endblock sidebar %}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% else %}
        <div class="col-sm-12 col-md-12  main">
        {% endif %}

    {% if messages %}
      <ul class="list-unstyled messages">
      {% for message in messages %}
        {% get_bootstrap_alert_msg_css_name message.tags as alert_tag %}
        <li class="alert alert-{{ alert_tag }} alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        {{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}

              {% block main_content %}
          {% endblock main_content %}
        </div>

        </div>
      </div>
      {% endblock content %}
    </div>


    {% block extra_javascript %}
    {% endblock extra_javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

indigo-web/indigo_ui/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact {% endblock title %}

{% block content %}
<div class="container">
    <h2>Contact</h2>
</div>
{% endblock %}

indigo-web/indigo_ui/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}

<div class="container">
<div style="margin-top: 140px; margin-bottom: 80px; text-align:center;">

    <div class="col-md-12">
        <img src="{% static 'img/logo_80.png' %}"/>
    </div>
    <br/>
    <div class="row" stlye="margin-top: 80px;">
      <div class="col-md-12" >
          <a class="btn btn-success" href="{% url 'users:auth_login' %}">Login</a>
      </div>
    </div>
</div>

{% endblock content %}

indigo-web/indigo_ui/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<div class="row">
  <br/><br/>
  <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
  <div class="well">
    <form id="loginForm" method="POST" action="{% url 'users:auth_login' %}" novalidate="novalidate">
      {% csrf_token %}
      <div class="form-group">
        <label for="username" class="control-label">Username</label>
        <input type="text" class="form-control" id="username" name="username" value="" required="" title="Please enter you username" placeholder="Username">
        <span class="help-block"></span>
      </div>
      <div class="form-group">
        <label for="password" class="control-label">Password</label>
        <input type="password" class="form-control" id="password" name="password" value="" required="" title="Please enter your password" placeholder="Password">
        <span class="help-block"></span>
      </div>
      <div id="loginErrorMsg" class="alert alert-error hide">Wrong username or password</div>
      <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" id="remember"> Remember login
        </label>
        <p class="help-block">(if this is a private computer)</p>
      </div>
      <button type="submit" class="btn btn-success btn-block">Login</button>
      <a href="/forgot/" class="btn btn-default btn-block">Help to login</a>
    </form>
  </div>
 </div>
</div>


{% endblock %}

{% block extra_javascript %}

{% endblock extra_javascript %}